-- MySQL Script generated by MySQL Workbench
-- Sat Apr 27 21:11:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema kdelectronics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kdelectronics` ;

-- -----------------------------------------------------
-- Schema kdelectronics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kdelectronics` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `kdelectronics` ;

-- -----------------------------------------------------
-- Table `kdelectronics`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kdelectronics`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kdelectronics`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kdelectronics`.`productos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio_base` DECIMAL(10,2) NOT NULL,
  `precio_venta` DECIMAL(10,2) NOT NULL,
  `categoria` VARCHAR(50) NULL DEFAULT NULL,
  `cantidad_disponible` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `kdelectronics`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kdelectronics`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL DEFAULT NULL,
  `codigo_producto` INT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `fecha_pedido` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `kdelectronics`.`clientes` (`id_cliente`),
  CONSTRAINT `pedidos_ibfk_2`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `kdelectronics`.`productos` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_cliente` ON `kdelectronics`.`pedidos` (`id_cliente` ASC) VISIBLE;

CREATE INDEX `codigo_producto` ON `kdelectronics`.`pedidos` (`codigo_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
